Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Blogger.Data;
using Blogger.Helpers.CustomAttributes;
using Blogger.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Logging;

namespace Blogger.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoryController(ApplicationDbContext _CONTEXT)
        {
            _context = _CONTEXT;
        }
        [Route("/Category/Lists")]
        public async Task<IActionResult> List()
        {
            var categories = await _context.Categories.ToListAsync();
            return View(categories);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await BindSelectList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.Slug = category.Name.GetBlogUrl();
                await _context.Categories.AddAsync(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            else
            {
                await BindSelectList();
                ModelState.AddModelError("", "Check the Required Fields!");
                return View(category);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
                return NotFound("Invalid ID");
            var model = await _context.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (model != null)
            {
                await BindSelectList();
                return View(model);
            }
            return NotFound("Category NOT FOUND!");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id <= 0)
                return NotFound("Invalid ID");
            if (ModelState.IsValid)
            {
                var ExistingModel = await _context.Categories.FindAsync(id);
                if (ExistingModel != null)
                {
                    ExistingModel.Slug = category.Name.GetBlogUrl();
                    ExistingModel.Name = category.Name;
                    ExistingModel.ParentId = category.ParentId;
                    ExistingModel.Content = category.Content;
                    ExistingModel.Status = category.Status;
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(List));
            }
            else
            {
                await BindSelectList();
                ModelState.AddModelError("", "Check Required Fields!");
                return View(category);
            }
        }
        public async Task<IActionResult> Details([FromRoute] int id)
        {
            if(id <= 0)
                return BadRequest("Invalid ID");
            var model = await _context.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if(model != null)
                return View(model);
            return NotFound("Categories Not Found!");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            if(id <= 0)
                return NotFound("Invalid Id");
            var model = await _context.Categories.FirstOrDefaultAsync(x => x.Id == id);
            var models = await _context.Categories.Where(x => x.ParentId == model.Id).ToListAsync();
            if(model != null || models != null)
            {
                
                _context.Categories.Remove(model);
                _context.Categories.RemoveRange(models);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(List));
        }

        private async Task BindSelectList()
        {
            ViewBag.Lists = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using AspNetCoreGeneratedDocument;
using Blogger.Data;
using Blogger.Enums;
using Blogger.Helpers.CustomAttributes;
using Blogger.Models;
using Blogger.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Blogger.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PostController(ApplicationDbContext dbContext)
        {
            _context = dbContext;
        }
        // private List<Post> _posts = PostService.GetAllPosts();

        //Search logic
        public async Task<IActionResult> List([FromQuery(Name = "search")] string search_key, Status? status)
        {
            List<Post> posts = new List<Post>();
            if (string.IsNullOrEmpty(search_key) && status == null)
            {
                posts = await _context.Posts.ToListAsync();
                return View(posts);
            }
            else if (status == null && !string.IsNullOrEmpty(search_key))
            {
                var post = await _context.Posts.Where(x => x.Content.ToLower().Contains(search_key.ToLower())).ToListAsync();
                return View(post);
            }
            else if (status != null && string.IsNullOrEmpty(search_key))
            {
                var post = await _context.Posts.Where(x => x.Status == status).ToListAsync();
                return View(post);
            }
            else
            {
                var post = await _context.Posts.Where(x => x.Content.ToLower().Contains(search_key.ToLower()) && x.Status == status).ToListAsync();
                return View(post);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await BindSelectListCategories();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Post post)
        {
            if (ModelState.IsValid)
            {
                Post Post = new Post()
                {
                    Content = post.Content,
                    Slug = post.Title.GetBlogUrl(),
                    CategoryId = post.Category.Id,
                    Category = post.Category,
                    Status = post.Status,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    PublishedAt = DateTime.Now,
                    Title = post.Title
                };

                await _context.Posts.AddAsync(Post);
                await _context.SaveChangesAsync();
                TempData["success-messege"] = "Post created successfully!";
                return RedirectToAction("List");
            }
            ModelState.AddModelError(" ", "Check Required Fields!");
            await BindSelectListCategories();
            return View(post);
        }
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
                return BadRequest("Invalid Id");
            var post = await _context.Posts.FirstOrDefaultAsync(x => x.Id == id);
            if (post == null)
                return NotFound("Post Not Found!");
            return View(post);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Post post)
        {
            if (ModelState.IsValid)
            {
                var ExistingPosts = _context.Posts.FirstOrDefault(x => x.Id == id);
                ExistingPosts.CategoryId = post.CategoryId;
                ExistingPosts.Content = post.Content;
                ExistingPosts.CreatedAt = post.CreatedAt;
                ExistingPosts.PublishedAt = post.PublishedAt;
                ExistingPosts.UpdatedAt = post.UpdatedAt;
                ExistingPosts.Slug = post.Title.GetBlogUrl();
                ExistingPosts.Media = post.Media;
                ExistingPosts.Status = post.Status;
                ExistingPosts.UserId = post.UserId;
                ExistingPosts.Title = post.Title;
                await _context.SaveChangesAsync(true);
                TempData["success-messege"] = "Post Updated Successfully!";
                return RedirectToAction(nameof(List));
            }
            ModelState.AddModelError(" ", "Check Required Fields!");
            return View(post);
        }
        [HttpGet]
        public async Task<IActionResult> Details([FromRoute] int id)
        {
            if (id <= 0)
                return BadRequest("Invalid Id");
            var model = await _context.Posts.FirstOrDefaultAsync(x => x.Id == id);
            if (model != null)
                return View(model);
            return NotFound("Post Not Found!");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            if (id <= 0)
                return BadRequest("Invalid Id");
            var model = await _context.Posts.FirstOrDefaultAsync(x => x.Id == id);
            if (model == null)
                return NotFound("Post Not Found!");

            _context.Posts.Remove(model);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }
        private async Task BindSelectListCategories()
        {
            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Blogger.Data;
using Blogger.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Blogger.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserController(ApplicationDbContext _context)
        {
            this._context = _context;
        }
        // Search Logic
        public async Task<IActionResult> List([FromQuery(Name = "search")] string search_key)
        {
            List<User> users = new List<User>();
            if(string.IsNullOrEmpty(search_key))
            {
                users = await _context.Users.ToListAsync();
                return View(User);
            }
            else
            {
                var Getusers = await _context.Users.Where(x => x.FirstName.ToLower().Contains(search_key.ToLower()) || x.Email.ToLower().Contains(search_key.ToLower()) || x.LastName.ToLower().Contains(search_key.ToLower()) || x.MiddleName.ToLower().Contains(search_key.ToLower())).ToListAsync();
                return View(Getusers);
            }
        }
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var users = await _context.Users.ToListAsync();
            return View(users);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if(id <= 0)
                return BadRequest("Invalid Id: User Not Found");
            else
            {
                var user = await _context.Users.FindAsync(id);
                if(user != null)
                {
                    return View(user);
                }
                return BadRequest("User Not Found");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if(ModelState.IsValid)
            {
                User SetUser = new User()
                {
                    FirstName = user.FirstName,
                    MiddleName = user.MiddleName,
                    LastName = user.LastName,
                    Phone = user.Phone,
                    Email = user.Email,
                    Password = user.Password,
                    RejisteredAt = DateTime.Now,
                    LastLogin = DateTime.Now,
                    Intro = user.Intro,
                    Profile = "/images/user.png"
                };
                await _context.Users.AddAsync(SetUser);
                await _context.SaveChangesAsync();
                TempData["success-messege"] = "User Created Successfully!";
                return RedirectToAction(nameof(List));
            }
            ModelState.AddModelError("", "Check the Required Fields!");
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int ID, User user)
        {
            if(ID <= 0)
                return BadRequest("Invalid Id");
            if(ModelState.IsValid)
            {
                var ExistingUser = _context.Users.FirstOrDefault(x => x.Id == ID);
                ExistingUser.FirstName = user.FirstName;
                ExistingUser.Email = user.Email;
                ExistingUser.LastName = user.LastName;
                ExistingUser.MiddleName = user.MiddleName;
                ExistingUser.Phone = user.Phone;
                ExistingUser.Password = user.Password;
                ExistingUser.RejisteredAt = user.RejisteredAt;
                ExistingUser.LastLogin = user.LastLogin;
                ExistingUser.Intro = user.Intro;
                ExistingUser.Profile = user.Profile;
                await _context.SaveChangesAsync(true);
                TempData["success-messege"] = "User Updated Successfully!";
                return RedirectToAction(nameof(List));
            }
            ModelState.AddModelError("", "Check Required Fields");
            return View(user);
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var user = await _context.Users.FindAsync(id);
            return View(user);
        }
        
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            if(id <= 0)
            {
                return BadRequest("Invalid ID");
            }
            var model = await _context.Users.FirstOrDefaultAsync(x => x.Id == id);
            if(model != null)
            {
                _context.Users.Remove(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return BadRequest("Usesr Not Found!");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/Common/_SidebarPartial.cshtml
<div class="vertical-menu">

    <div data-simplebar="init" class="h-100">
        <div class="simplebar-wrapper" style="margin: 0px;">
            <div class="simplebar-height-auto-observer-wrapper">
                <div class="simplebar-height-auto-observer"></div>
            </div>
            <div class="simplebar-mask">
                <div class="simplebar-offset" style="right: -17px; bottom: 0px;">
                    <div class="simplebar-content-wrapper" style="height: 100%; overflow: hidden scroll;">
                        <div class="simplebar-content" style="padding: 0px;">

                            <!--- Sidemenu -->
                            <div id="sidebar-menu" class="mm-active">
                                <!-- Left Menu Start -->
                                <ul class="metismenu list-unstyled mm-show" id="side-menu">
                                    <li class="menu-title" key="t-menu">Menu</li>

                                    <li class="mm-active">
                                        <a asp-action="Index" asp-controller="Home" class="waves-effect mm-active">
                                            <i class="bx bx-home-circle"></i><span
                                                class="badge rounded-pill bg-info float-end">04</span>
                                            <span key="t-dashboards">Dashboards</span>
                                        </a>
                                        <ul class="sub-menu mm-collapse mm-show" aria-expanded="false">
                                            <li class="mm-active"><a href="index.html" key="t-default"
                                                    class="active">Default</a></li>
                                            <li><a href="dashboard-saas.html" key="t-saas">Saas</a></li>
                                            <li><a href="dashboard-crypto.html" key="t-crypto">Crypto</a></li>
                                            <li><a href="dashboard-blog.html" key="t-blog">Blog</a></li>
                                        </ul>
                                    </li>

                                    <li>
                                        <ul class="sub-menu mm-collapse" aria-expanded="true">
                                            <li>
                                                <a href="javascript: void(0);" class="has-arrow"
                                                    key="t-vertical">Vertical</a>
                                                <ul class="sub-menu mm-collapse" aria-expanded="true">
                                                    <li><a href="layouts-light-sidebar.html" key="t-light-sidebar">Light
                                                            Sidebar</a></li>
                                                    <li><a href="layouts-compact-sidebar.html"
                                                            key="t-compact-sidebar">Compact Sidebar</a></li>
                                                    <li><a href="layouts-icon-sidebar.html" key="t-icon-sidebar">Icon
                                                            Sidebar</a></li>
                                                    <li><a href="layouts-boxed.html" key="t-boxed-width">Boxed Width</a>
                                                    </li>
                                                    <li><a href="layouts-preloader.html" key="t-preloader">Preloader</a>
                                                    </li>
                                                    <li><a href="layouts-colored-sidebar.html"
                                                            key="t-colored-sidebar">Colored Sidebar</a></li>
                                                    <li><a href="layouts-scrollable.html"
                                                            key="t-scrollable">Scrollable</a></li>
                                                </ul>
                                            </li>

                                            <li>
                                                <a href="javascript: void(0);" class="has-arrow"
                                                    key="t-horizontal">Horizontal</a>
                                                <ul class="sub-menu mm-collapse" aria-expanded="true">
                                                    <li><a href="layouts-horizontal.html"
                                                            key="t-horizontal">Horizontal</a></li>
                                                    <li><a href="layouts-hori-topbar-light.html"
                                                            key="t-topbar-light">Topbar light</a></li>
                                                    <li><a href="layouts-hori-boxed-width.html"
                                                            key="t-boxed-width">Boxed width</a></li>
                                                    <li><a href="layouts-hori-preloader.html"
                                                            key="t-preloader">Preloader</a></li>
                                                    <li><a href="layouts-hori-colored-header.html"
                                                            key="t-colored-topbar">Colored Header</a></li>
                                                    <li><a href="layouts-hori-scrollable.html"
                                                            key="t-scrollable">Scrollable</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>

                                    <li class="menu-title" key="t-apps">Apps</li>

                                    <li>
                                        <a asp-action="List" asp-controller="Post" class="waves-effect">
                                            <i class="bx bx-edit"></i>
                                            <span key="t-calendar">Posts</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-action="Lists" asp-controller="Category" class="waves-effect">
                                            <i class='bx bx-category'></i>
                                            <span key="t-calendar">Categories</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-action="List" asp-controller="User" class="waves-effect">
                                            <i class="bx bx-group"></i>
                                            <span key="t-calendar">Users</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- Sidebar -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="simplebar-placeholder" style="width: auto; height: 1321px;"></div>
        </div>
        <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
            <div class="simplebar-scrollbar" style="transform: translate3d(0px, 0px, 0px); display: none;"></div>
        </div>
        <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
            <div class="simplebar-scrollbar"
                style="height: 239px; transform: translate3d(0px, 0px, 0px); display: block;"></div>
        </div>
    </div>
</div>

Views/Shared/Common/_TitleNavigationPartial.cshtml
@model (string title, string url, string urlName, string currentPage)
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0 font-size-18">@Model.title</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="@Model.url">@Model.urlName</a></li>
                    <li class="breadcrumb-item active">@Model.currentPage</li>
                </ol>
            </div>
        </div>
    </div>
</div>